name: Test

on:
  push:
    branches-ignore:
      # Master does just a deploy
      - 'master'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
    - name: Code checkout
      uses: actions/checkout@v2

    - name: Restore asdf-vm
      id: asdf-vm-cache
      uses: actions/cache@v2
      with:
        path: ~/.asdf
        key: 20.04-asdf-${{ hashFiles('.tool-versions') }}

    - name: Install asdf-vm
      uses: asdf-vm/actions/install@v1
      if: steps.asdf-vm-cache.outputs.cache-hit != 'true'

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: 20.04-mix-${{ hashFiles('**/mix.lock') }}

    - name: The works
      run: make test
